# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-27 03:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yadel_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=125)),
                ('email', models.CharField(max_length=225)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='LatestNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_content', models.CharField(max_length=300)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=125)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('contact_email', models.CharField(max_length=225)),
            ],
        ),
        migrations.AddField(
            model_name='medianames',
            name='contact_persons',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publication',
            name='date_published',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=b'publication/%Y-%M-%D'),
        ),
        migrations.AddField(
            model_name='publication',
            name='person_to_quote',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='persons_position',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='publish_online',
            field=models.BooleanField(default=False, verbose_name=b'Do you also want online publication of the chosen media? '),
        ),
        migrations.AddField(
            model_name='publication',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Edited_and_published_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publication',
            name='redirect_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='content',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='media',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pictures',
            field=models.FileField(blank=True, null=True, upload_to=b'media/'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='press_material',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='publication',
            name='status',
            field=models.CharField(choices=[(b'new', b'new'), (b'published', b'published'), (b'processing', b'processing'), (b'rejected', b'rejected')], default=b'new', max_length=25),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='title',
            field=models.CharField(max_length=15),
        ),
        migrations.AddField(
            model_name='mediacontact',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yadel_main.MediaNames'),
        ),
    ]
