# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-27 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yadel_main', '0002_auto_20160527_0336'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to=b'publication/%Y-%M-%D')),
            ],
        ),
        migrations.RemoveField(
            model_name='publication',
            name='document',
        ),
        migrations.AddField(
            model_name='pubdocument',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yadel_main.Publication', verbose_name=b'Related publication'),
        ),
    ]
