# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yadel_main', '0002_auto_20160412_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='publish_online',
            field=models.BooleanField(default=False),
        ),
    ]
