# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-28 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yadel_main', '0003_auto_20160527_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubdocument',
            name='publication',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yadel_main.Publication', verbose_name=b'Related publication'),
        ),
    ]
