# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-01 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yadel_main', '0004_auto_20160528_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='registration_code',
            field=models.CharField(max_length=50),
        ),
    ]
