# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-13 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yadel_main', '0004_auto_20160412_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='media',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='publication',
            name='press_material',
            field=models.CharField(max_length=125),
        ),
    ]
