# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-17 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yadel_main', '0006_auto_20160417_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='redirect_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
