# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-17 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yadel_main', '0007_publication_redirect_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='redirect_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='status',
            field=models.CharField(choices=[(b'new', b'new'), (b'published', b'published'), (b'pending', b'pending'), (b'rejected', b'rejected')], default=b'new', max_length=25),
        ),
    ]
