# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-20 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yadel_main', '0009_auto_20160420_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='date_published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
