# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-28 23:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yadel_main', '0010_auto_20160420_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=175)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('contact_persons', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='publication',
            name='content',
            field=models.TextField(max_length=3000),
        ),
    ]
