# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-28 23:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yadel_main', '0011_auto_20160428_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediahouse',
            name='contact_persons',
        ),
        migrations.AddField(
            model_name='medianames',
            name='contact_persons',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MediaHouse',
        ),
    ]
