# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-30 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yadel_main', '0013_mediacontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='status',
            field=models.CharField(choices=[(b'new', b'new'), (b'published', b'published'), (b'processing', b'processing'), (b'rejected', b'rejected')], default=b'new', max_length=25),
        ),
    ]
