# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-07 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yadel_main', '0014_auto_20160430_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=125)),
                ('email', models.CharField(max_length=225)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
    ]
