# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-07 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yadel_main', '0015_contactmessages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMessages',
            new_name='ClientFeedback',
        ),
    ]
