# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-08 23:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yadel_main', '0017_latestnews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='document',
        ),
        migrations.AlterField(
            model_name='medianames',
            name='contact_persons',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
